yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information
site_name: 基岩文档
site_url: https://miemiemethod.github.io/bedrock-docs/
edit_uri: edit/main/docs/
site_description: Minecraft基岩版开发文档

# Repository
repo_name: GitHub
repo_url: https://github.com/MiemieMethod/bedrock-docs

# Copyright
copyright: >
  Copyright &copy; 2024 Miemie Method & LPaicen – <a href="#__consent">更改Cookie设置</a> – 除非另有声明，本站内容采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0;vertical-align: text-bottom;" src="/bedrock-docs/assets/images/by-nc-sa.svg" />知识共享署名-非商业性使用-相同方式共享</a>授权，附加条款亦可能应用。

# Configuration
theme:
  name: material
  language: zh
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换至浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: 切换至系统偏好
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

# Hooks
hooks:
  - overrides/hooks/shortcodes.py
  - overrides/hooks/wikilink.py
  - overrides/hooks/abbr.py

# Additional configuration
extra:
  status:
    new: 最近添加
    deprecated: 已弃用
  analytics:
    provider: google
    property: G-5E7Q5MKZZ8
    feedback:
      title: 本页是否有帮助？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 帮大忙了
          data: 1
          note: >-
            感谢您的反馈！
        - icon: material/emoticon-sad-outline
          name: 改需改进
          data: 0
          note: >- 
            感谢您的反馈！或许您可以通过进一步填写<a href="..." target="_blank" rel="noopener">反馈问卷</a>来帮助我们改进。
  consent:
    title: 同意Cookie
    description: >- 
      我们利用Cookie来记住您的访问记录和喜好，同时也用来评估我们的文档是否有效，以及用户是否能找到他们想要的信息。如果您同意，那么您就是在帮助我们不断优化我们的文档，非常感谢！<small>您随时可以在页面底部更改您的Cookie设置。</small>
    cookies:
      analytics:
        name: Google分析
        checked: true
      github:
        name: GitHub
        checked: true
    actions:
      - accept
      - manage
      - reject
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MiemieMethod/bedrock-docs
extra_css:
  - assets/stylesheets/fonts.css
  - assets/stylesheets/code.css
  - assets/stylesheets/banner.css
  - assets/stylesheets/keys.css
  - assets/stylesheets/magiclink.css
  - assets/stylesheets/progressbar.css
  - assets/stylesheets/admonition.css
  - assets/stylesheets/badge.css
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/uml.js
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  # - assets/javascripts/tablesort.js
  # - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/viz-standalone.js
  - assets/javascripts/viz.js

# Plugins
plugins:
  - search
  - social
  - blog
  - rss
  - tags
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: MiemieMethod/bedrock-docs
      branch: main
  - glightbox:
       skip_classes:
         - skip-image
       auto_caption: true
       background: gainsboro

# Extensions
markdown_extensions:
  - abbr
  # - admonition
  - attr_list
  # - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: 该段落的引用链接
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - smarty:
      smart_quotes: false
  # - wikilinks:
  #     base_url: https://wiki.mcbe-dev.net/p/
  #     build_url: !!python/name:tools.wikilink_parser.wiki_url_builder
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  # - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
      # auto_title: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {kwds: {mode: generic}}
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
        - name: md-render
          class: md-render
          format: !!python/name:tools.pymdownx_md_render.md_sub_render
        - name: viz
          class: viz
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      dedent_subsections: true
      base_path: 'includes/'
      auto_append:
        - abbreviations.md
        - glossaries.md
  # - pymdownx.tabbed:
  #     alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tools.collapse_code:
      expand_text: ''
      collapse_text: ''
      expand_title: '展开'
      collapse_title: '收起'
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: MiemieMethod
      repo: bedrock-docs
      normalize_issue_symbols: true
      labels:
        commit: '提交'
        compare: '比较'
        issue: '议题'
        pull: '拉取请求'
        mention: '用户'
        repository: '仓库'
        discuss: '讨论'
  - pymdownx.smartsymbols
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.progressbar
  - pymdownx.striphtml
  - pymdownx.saneheaders
  - pymdownx.blocks.admonition:
      types:
      - name: new
        class: new
        title: 新功能
      - name: settings
        class: settings
        title: 设置
      - name: note
        class: note
        title: 注意
      - name: abstract
        class: abstract
        title: 摘要
      - name: info
        class: info
        title: 信息
      - name: tip
        class: tip
        title: 提示
      - name: success
        class: success
        title: 成功
      - name: question
        class: question
        title: 问题
      - name: warning
        class: warning
        title: 警告
      - name: failure
        class: failure
        title: 失败
      - name: danger
        class: danger
        title: 危险
      - name: bug
        class: bug
        title: 漏洞
      - name: example
        class: example
        title: 示例
      - name: quote
        class: quote
        title: 引用
  - pymdownx.blocks.details:
      types:
      - name: details-new
        class: new
        title: 新功能
      - name: details-settings
        class: settings
        title: 设置
      - name: details-note
        class: note
        title: 注意
      - name: details-abstract
        class: abstract
        title: 摘要
      - name: details-info
        class: info
        title: 信息
      - name: details-tip
        class: tip
        title: 提示
      - name: details-success
        class: success
        title: 成功
      - name: details-question
        class: question
        title: 问题
      - name: details-warning
        class: warning
        title: 警告
      - name: details-failure
        class: failure
        title: 失败
      - name: details-danger
        class: danger
        title: 危险
      - name: details-bug
        class: bug
        title: 漏洞
      - name: details-example
        class: example
        title: 示例
      - name: details-quote
        class: quote
        title: 引用
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

# Page tree
nav:
  - 首页:
    - 欢迎: index.md
    - 贡献: contributing.md
  - 文档:
    - docs/index.md
  - 教程:
    - guides/index.md
    - 附加包:
      - guides/addons/index.md
      - 认识附加包: guides/addons/understanding-addons.md
      - 制作纹理包: guides/addons/creating-texture-packs.md
      - 本地化: guides/addons/localization.md
      - 使用子包: guides/addons/utilizing-sub-packs.md
      - 数据驱动:
        - guides/addons/data-driven/index.md
        - 制作模型: guides/addons/data-driven/creating-models.md
        - 认识Molang: guides/addons/data-driven/understanding-molang.md
        - 自定义实体:
          - guides/addons/data-driven/entities/index.md
          - 第一个实体: guides/addons/data-driven/entities/adding-custom-entities.md
          - 动画与动画控制器: guides/addons/data-driven/entities/animations-and-animation-controllers.md
          - 添加附着物: guides/addons/data-driven/entities/adding-attachables.md
          - 创建NPC: guides/addons/data-driven/entities/adding-npc.md
        - 自定义方块:
          - guides/addons/data-driven/blocks/index.md
          - 第一个方块: guides/addons/data-driven/blocks/adding-custom-blocks.md
          - 自定义工作台: guides/addons/data-driven/blocks/adding-custom-crafting-table.md
        - 自定义物品:
          - guides/addons/data-driven/items/index.md
          - 第一个物品: guides/addons/data-driven/items/adding-custom-items.md
        - 自定义粒子: guides/addons/data-driven/adding-custom-particles.md
        - 自定义声音: guides/addons/data-driven/adding-custom-sounds.md
        - 自定义配方: guides/addons/data-driven/adding-custom-recipes.md
        - 自定义战利品表: guides/addons/data-driven/adding-custom-loot-tables.md
        - 自定义迷雾: guides/addons/data-driven/adding-custom-fogs.md
        - 自定义地物: guides/addons/data-driven/adding-custom-features.md
        - 自定义生物群系: guides/addons/data-driven/adding-custom-biomes.md
        - 自定义维度: guides/addons/data-driven/adding-custom-dimensions.md
        - 自定义功能域: guides/addons/data-driven/adding-custom-volumes.md
      - 使用函数: guides/addons/utilizing-functions.md
      - 创建世界模板: guides/addons/create-a-world-template.md
      - 制作皮肤包: guides/addons/creating-skin-packs.md
      - 制作结构包: guides/addons/creating-structure-packs.md
      - 脚本API:
        - guides/addons/script-api/index.md
        - 构建第一个脚本: guides/addons/script-api/building-your-first-scripts.md
        - 使用TypeScript构建包: guides/addons/script-api/building-packs-with-typescript.md
      - 模组SDK:
        - guides/addons/modsdk/index.md
    - 社区模组:
      - guides/community-mods/index.md
      - ICMod:
        - guides/community-mods/icmod/index.md
      - ModPE:
        - guides/community-mods/modpe/index.md
    - 软件工具:
      - guides/tools/index.md
      - Blockbench:
        - guides/tools/blockbench/index.md
        - 使用指南: guides/tools/blockbench/how-to-use.md
        - 制作Minecraft风格标题: guides/tools/blockbench/creating-minecraft-style-title.md
      - 编辑器: guides/tools/editor.md
    - 服务端:
      - guides/servers/index.md
    - 着色器:
      - guides/shaders/index.md
      - 认识着色器: guides/shaders/understanding-shaders.md
      - 使用并自定义延迟渲染: guides/shaders/getting-started-with-deferred-lighting.md
      - 启用光线追踪并制作PBR包: guides/shaders/getting-started-with-ray-tracing.md
      - 中国版着色器:
        - guides/shaders/netease-shader/index.md
      - BetterRTX: guides/shaders/betterrtx.md
    - 杂项教程:
      - guides/misc/index.md
    - 过时教程:
      - guides/outdated/index.md
      - '1.16.100': 
        - guides/outdated/1.16.100/index.md
      - '1.10':
        - guides/outdated/1.10/index.md
  - 参考:
    - refs/index.md
    - 命令:
      - refs/commands/index.md
      - 列表:
        - <code>ability</code>: refs/commands/ability.md
        - <code>agent</code>: refs/commands/agent.md
        - <code>allowlist</code>: refs/commands/allowlist.md
        - <code>camera</code>: refs/commands/camera.md
        - <code>camerashake</code>: refs/commands/camerashake.md
        - <code>changesetting</code>: refs/commands/changesetting.md
        - <code>clear</code>: refs/commands/clear.md
        - <code>clearrealmevents</code>: refs/commands/clearrealmevents.md
        - <code>clearspawnpoint</code>: refs/commands/clearspawnpoint.md
        - <code>clone</code>: refs/commands/clone.md
        - <code>closewebsocket</code>: refs/commands/closewebsocket.md
        - <code>codebuilder</code>: refs/commands/codebuilder.md
        - <code>codebuilder_actorinfo</code>: refs/commands/codebuilder_actorinfo.md
        - <code>damage</code>: refs/commands/damage.md
        - <code>daylock</code>: refs/commands/daylock.md
        - <code>dedicatedwsserver</code>: refs/commands/dedicatedwsserver.md
        - <code>deop</code>: refs/commands/deop.md
        - <code>dialogue</code>: refs/commands/dialogue.md
        - <code>difficulty</code>: refs/commands/difficulty.md
        - <code>effect</code>: refs/commands/effect.md
        - <code>enableencryption</code>: refs/commands/enableencryption.md
        - <code>enchant</code>: refs/commands/enchant.md
        - <code>event</code>: refs/commands/event.md
        - <code>execute</code>: refs/commands/execute.md
        - <code>fill</code>: refs/commands/fill.md
        - <code>fog</code>: refs/commands/fog.md
        - <code>function</code>: refs/commands/function.md
        - <code>gamemode</code>: refs/commands/gamemode.md
        - <code>gamerule</code>: refs/commands/gamerule.md
        - <code>gametest</code>: refs/commands/gametest.md
        - <code>getchunkdata</code>: refs/commands/getchunkdata.md
        - <code>getchunks</code>: refs/commands/getchunks.md
        - <code>geteduserverinfo</code>: refs/commands/geteduserverinfo.md
        - <code>getspawnpoint</code>: refs/commands/getspawnpoint.md
        - <code>gettopsolidblock</code>: refs/commands/gettopsolidblock.md
        - <code>give</code>: refs/commands/give.md
        - <code>globalpause</code>: refs/commands/globalpause.md
        - <code>help</code>: refs/commands/help.md
        - <code>hud</code>: refs/commands/hud.md
        - <code>immutableworld</code>: refs/commands/immutableworld.md
        - <code>inputpermission</code>: refs/commands/inputpermission.md
        - <code>kick</code>: refs/commands/kick.md
        - <code>kill</code>: refs/commands/kill.md
        - <code>lesson</code>: refs/commands/lesson.md
        - <code>list</code>: refs/commands/list.md
        - <code>listd</code>: refs/commands/listd.md
        - <code>locate</code>: refs/commands/locate.md
        - <code>loot</code>: refs/commands/loot.md
        - <code>me</code>: refs/commands/me.md
        - <code>mobevent</code>: refs/commands/mobevent.md
        - <code>music</code>: refs/commands/music.md
        - <code>op</code>: refs/commands/op.md
        - <code>particle</code>: refs/commands/particle.md
        - <code>permission</code>: refs/commands/permission.md
        - <code>playanimation</code>: refs/commands/playanimation.md
        - <code>playsound</code>: refs/commands/playsound.md
        - <code>project</code>: refs/commands/project.md
        - <code>querytarget</code>: refs/commands/querytarget.md
        - <code>recipe</code>: refs/commands/recipe.md
        - <code>reload</code>: refs/commands/reload.md
        - <code>reloadconfig</code>: refs/commands/reloadconfig.md
        - <code>replaceitem</code>: refs/commands/replaceitem.md
        - <code>resourceuri</code>: refs/commands/resourceuri.md
        - <code>ride</code>: refs/commands/ride.md
        - <code>save</code>: refs/commands/save.md
        - <code>say</code>: refs/commands/say.md
        - <code>schedule</code>: refs/commands/schedule.md
        - <code>scoreboard</code>: refs/commands/scoreboard.md
        - <code>script</code>: refs/commands/script.md
        - <code>scriptevent</code>: refs/commands/scriptevent.md
        - <code>sendshowstoreoffer</code>: refs/commands/sendshowstoreoffer.md
        - <code>setblock</code>: refs/commands/setblock.md
        - <code>setmaxplayers</code>: refs/commands/setmaxplayers.md
        - <code>setworldspawn</code>: refs/commands/setworldspawn.md
        - <code>spawnpoint</code>: refs/commands/spawnpoint.md
        - <code>spreadplayers</code>: refs/commands/spreadplayers.md
        - <code>stop</code>: refs/commands/stop.md
        - <code>stopsound</code>: refs/commands/stopsound.md
        - <code>structure</code>: refs/commands/structure.md
        - <code>summon</code>: refs/commands/summon.md
        - <code>tag</code>: refs/commands/tag.md
        - <code>takepicture</code>: refs/commands/takepicture.md
        - <code>teleport</code>: refs/commands/teleport.md
        - <code>tell</code>: refs/commands/tell.md
        - <code>tellraw</code>: refs/commands/tellraw.md
        - <code>testfor</code>: refs/commands/testfor.md
        - <code>testforblock</code>: refs/commands/testforblock.md
        - <code>testforblocks</code>: refs/commands/testforblocks.md
        - <code>tickingarea</code>: refs/commands/tickingarea.md
        - <code>time</code>: refs/commands/time.md
        - <code>title</code>: refs/commands/title.md
        - <code>titleraw</code>: refs/commands/titleraw.md
        - <code>toggledownfall</code>: refs/commands/toggledownfall.md
        - <code>transfer</code>: refs/commands/transfer.md
        - <code>volumearea</code>: refs/commands/volumearea.md
        - <code>weather</code>: refs/commands/weather.md
        - <code>worldbuilder</code>: refs/commands/worldbuilder.md
        - <code>wsserver</code>: refs/commands/wsserver.md
        - <code>xp</code>: refs/commands/xp.md
    - 附表:
      - refs/tables/index.md
      - 方块:
        - 原版方块标签: refs/tables/blocks/vanilla_tags.md
      - 物品:
        - 原版物品标签: refs/tables/items/vanilla_tags.md
  - 专栏:
    - blog/index.md