# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: 基岩文档
site_url: https://miemiemethod.github.io/bedrock-docs/
repo_name: GitHub
repo_url: https://github.com/MiemieMethod/bedrock-docs
edit_uri: edit/main/docs/
site_description: Minecraft基岩版开发文档
theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换至浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: 切换至系统偏好
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.tooltips
    - content.code.copy
extra:
  consent:
    title: 同意Cookie
    description: >- 
      我们利用Cookie来记住您的访问记录和喜好，同时也用来评估我们的文档是否有效，以及用户是否能找到他们想要的信息。如果您同意，那么您就是在帮助我们不断优化我们的文档，非常感谢！<small>您随时可以在页面底部更改您的Cookie设置。</small>
    cookies:
      analytics:
        name: Google分析
        checked: true
      github:
        name: GitHub
        checked: true
    actions:
      - accept
      - manage
      - reject
copyright: >
  Copyright &copy; 2024 Miemie Method –
  <a href="#__consent">更改Cookie设置</a>
extra_css:
  - stylesheets/fonts.css
  - stylesheets/collapse.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
plugins:
  - search
  - social
  - blog
  - rss
  - tags
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: MiemieMethod/bedrock-docs
      branch: main
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: 该段落的引用链接
  - tables
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
      # auto_title: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {kwds: {mode: generic}}
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
        - name: md-render
          class: md-render
          format: !!python/name:tools.pymdownx_md_render.md_sub_render
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tools.collapse_code:
      expand_text: ''
      collapse_text: ''
      expand_title: '展开'
      collapse_title: '收起'